//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetGpsToOpcAndDb.WbService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoSuchAlgorithmException", Namespace="http://security.java")]
    [System.SerializableAttribute()]
    public partial class NoSuchAlgorithmException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webService.ysu.com", ConfigurationName="WbService.IWbServicePortType")]
    public interface IWbServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GetGpsToOpcAndDb.WbService.NoSuchAlgorithmException), Action="", Name="NoSuchAlgorithmException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        bool save_gps_machines(string in0, System.Nullable<double> in1, System.Nullable<double> in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<bool> save_gps_machinesAsync(string in0, System.Nullable<double> in1, System.Nullable<double> in2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWbServicePortTypeChannel : GetGpsToOpcAndDb.WbService.IWbServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WbServicePortTypeClient : System.ServiceModel.ClientBase<GetGpsToOpcAndDb.WbService.IWbServicePortType>, GetGpsToOpcAndDb.WbService.IWbServicePortType {
        
        public WbServicePortTypeClient() {
        }
        
        public WbServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WbServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WbServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WbServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool save_gps_machines(string in0, System.Nullable<double> in1, System.Nullable<double> in2) {
            return base.Channel.save_gps_machines(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<bool> save_gps_machinesAsync(string in0, System.Nullable<double> in1, System.Nullable<double> in2) {
            return base.Channel.save_gps_machinesAsync(in0, in1, in2);
        }
    }
}
